import Home from './HomePage'
import About from './AboutPage'
import Error from './ErrorPage'
import Products from './ProductsPage'
import SingleProduct from './SingleProductPage'
import Cart from './CartPage'
import Checkout from './CheckoutPage'
import PrivateRoute from './PrivateRoute'
import AuthWrapper from './AuthWrapper'
export {Home, About, Error, Products, SingleProduct, Cart, Checkout, PrivateRoute, AuthWrapper}